version: 1.0
name: WingsOfFireAccessories
main: com.wingsoffireserver.wingsoffire.Main
api-version: 1.13
commands:
  ab:
    aliases: [accessorybag]
  activeplayer:
    aliases: []
  customItems:
    aliases: []
  animus:
    aliases: []
  spawnstudynpc:
    aliases: []
  aadmin:
    aliases: [animusadmin]